application: xmltopoints
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: xmltopoints.app

builtins:
- datastore_admin: on
- appstats: on

libraries:
- name: django
  version: "1.2"
